//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humans.Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HumansEntities : DbContext
    {
        public HumansEntities()
            : base("name=HumansEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NotificationType> NotificationTypes { get; set; }
        public DbSet<Sport> Sports { get; set; }
        public DbSet<SportCategory> SportCategories { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<UserMessage> UserMessages { get; set; }
        public DbSet<UserNotification> UserNotifications { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UserSport> UserSports { get; set; }
        public DbSet<UserUser> UserUsers { get; set; }
        public DbSet<UserVenue> UserVenues { get; set; }
        public DbSet<Venue> Venues { get; set; }
        public DbSet<VenueSport> VenueSports { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
    }
}
