//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humans.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportCategory
    {
        public SportCategory()
        {
            this.Sports = new HashSet<Sport>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Sport> Sports { get; set; }
    }
}
