//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humans.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport
    {
        public Sport()
        {
            this.UserSports = new HashSet<UserSport>();
            this.VenueSports = new HashSet<VenueSport>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Longname { get; set; }
        public int SportCategoryId { get; set; }
    
        public virtual SportCategory SportCategory { get; set; }
        public virtual ICollection<UserSport> UserSports { get; set; }
        public virtual ICollection<VenueSport> VenueSports { get; set; }
    }
}
