//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humans.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSport
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int SportId { get; set; }
        public bool Findable { get; set; }
        public string Note { get; set; }
        public int SkillLevel { get; set; }
    
        public virtual Sport Sport { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
