//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humans.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public Venue()
        {
            this.UserVenues = new HashSet<UserVenue>();
            this.VenueSports = new HashSet<VenueSport>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public int StateId { get; set; }
        public string Zip { get; set; }
        public string Description { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
        public string PlaceId { get; set; }
        public string Logo { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<UserVenue> UserVenues { get; set; }
        public virtual ICollection<VenueSport> VenueSports { get; set; }
    }
}
